Layer size is:  [3, 50, 50, 50, 50, 1]
Compiling model...
'compile' took 3.401515 s

Training model...

Warning: Rectangle boundary_normal called on vertices. You may use PDE(..., exclusions=...) to exclude the vertices.
Warning: Rectangle boundary_normal called on vertices. You may use PDE(..., exclusions=...) to exclude the vertices.
Error executing job with overrides: []
Traceback (most recent call last):
  File "/working_dir/./src/main.py", line 55, in main
    train.single_observer(prj, cfg.run, "0", cfg)
  File "/working_dir/src/train.py", line 101, in single_observer
    mo = train_model(run, cfg)
  File "/working_dir/src/train.py", line 38, in train_model
    mm = nhbo.create_nbho(name, cfg)
  File "/working_dir/src/nhbo.py", line 149, in create_nbho
    initial_losses = train.get_initial_loss(model)
  File "/working_dir/src/train.py", line 147, in get_initial_loss
    losshistory, _ = model.train(0)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/utils/internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 643, in train
    self._test()
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 832, in _test
    ) = self._outputs_losses(
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 551, in _outputs_losses
    outs = outputs_losses(inputs, targets, auxiliary_vars)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 322, in outputs_losses_train
    return outputs_losses(
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 310, in outputs_losses
    losses = losses_fn(targets, outputs_, loss_fn, inputs, self, aux=aux)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/data/data.py", line 13, in losses_train
    return self.losses(targets, outputs, loss_fn, inputs, model, aux=aux)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/data/pde.py", line 179, in losses
    error = bc.error(self.train_x, inputs, outputs, beg, end)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/icbc/initial_conditions.py", line 30, in error
    values = self.func(X, beg, end, aux_var)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/icbc/boundary_conditions.py", line 391, in wrapper_cache
    cache[key] = func(X[beg:end])
  File "/opt/conda/lib/python3.10/site-packages/deepxde/utils/internal.py", line 87, in wrapper
    return bkd.as_tensor(func(*args, **kwargs), dtype=config.real(bkd.lib))
  File "/working_dir/src/conditions.py", line 169, in ic_obs
    delta_t = parameters["Parameters"]["deltat"]
KeyError: 'deltat'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
