2024-06-25 17:18:42,321 INFO    MainThread:734 [wandb_setup.py:_flush():76] Current SDK version is 0.17.3
2024-06-25 17:18:42,322 INFO    MainThread:734 [wandb_setup.py:_flush():76] Configure stats pid to 734
2024-06-25 17:18:42,323 INFO    MainThread:734 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-06-25 17:18:42,324 INFO    MainThread:734 [wandb_setup.py:_flush():76] Loading settings from /working_dir/wandb/settings
2024-06-25 17:18:42,324 INFO    MainThread:734 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-25 17:18:42,325 INFO    MainThread:734 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-25 17:18:42,325 INFO    MainThread:734 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'src/main.py', 'program_abspath': '/working_dir/src/main.py', 'program': '/working_dir/./src/main.py'}
2024-06-25 17:18:42,325 INFO    MainThread:734 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-25 17:18:42,326 INFO    MainThread:734 [wandb_init.py:_log_setup():520] Logging user logs to /working_dir/wandb/run-20240625_171842-6ebyyum6/logs/debug.log
2024-06-25 17:18:42,327 INFO    MainThread:734 [wandb_init.py:_log_setup():521] Logging internal logs to /working_dir/wandb/run-20240625_171842-6ebyyum6/logs/debug-internal.log
2024-06-25 17:18:42,327 INFO    MainThread:734 [wandb_init.py:init():560] calling init triggers
2024-06-25 17:18:42,328 INFO    MainThread:734 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'activation': 'tanh', 'initial_weights_regularizer': True, 'initialization': 'Glorot normal', 'iterations': 30000, 'LBFGS': False, 'learning_rate': 0.001, 'num_dense_layers': 2, 'num_dense_nodes': 50, 'output_injection_gain': 50, 'resampling': True, 'resampler_period': 100}
2024-06-25 17:18:42,328 INFO    MainThread:734 [wandb_init.py:init():610] starting backend
2024-06-25 17:18:42,329 INFO    MainThread:734 [wandb_init.py:init():614] setting up manager
2024-06-25 17:18:42,351 INFO    MainThread:734 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-25 17:18:42,356 INFO    MainThread:734 [wandb_init.py:init():622] backend started and connected
2024-06-25 17:18:42,398 INFO    MainThread:734 [wandb_init.py:init():711] updated telemetry
2024-06-25 17:18:42,399 INFO    MainThread:734 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-25 17:18:44,572 ERROR   MainThread:734 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-06-25 17:18:44,574 ERROR   MainThread:734 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-06-25 17:18:46,055 WARNING MsgRouterThr:734 [router.py:message_loop():77] message_loop has been closed
