Layer size is:  [5, 50, 50, 1]
The model info are:  <deepxde.model.Model object at 0x40d8bfc400>
Compiling model...
'compile' took 2.587525 s

Training model...
Error executing job with overrides: []
Traceback (most recent call last):
  File "/working_dir/./src/main.py", line 54, in main
    train.single_observer(prj, cfg.run, "0", cfg)
  File "/working_dir/src/train.py", line 109, in single_observer
    mo = train_model(run, cfg)
  File "/working_dir/src/train.py", line 46, in train_model
    mm = pde.create_nbho(name, cfg)
  File "/working_dir/src/pde.py", line 230, in create_nbho
    initial_losses = train.get_initial_loss(model)
  File "/working_dir/src/train.py", line 155, in get_initial_loss
    losshistory, _ = model.train(0)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/utils/internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 636, in train
    self._test()
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 825, in _test
    ) = self._outputs_losses(
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 546, in _outputs_losses
    outs = outputs_losses(inputs, targets, auxiliary_vars)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 320, in outputs_losses_train
    return outputs_losses(
  File "/opt/conda/lib/python3.10/site-packages/deepxde/model.py", line 302, in outputs_losses
    outputs_ = self.net(inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/deepxde/nn/pytorch/fnn.py", line 43, in forward
    else self.activation(linear(x))
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (3161x3 and 5x50)

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
